#### 1. Import the numpy package under the name `np` (★☆☆)

import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)

In [12]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [21]:
x[4] = 1
print (x[4])

1.0


#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)

In [26]:
n = np.arange(10,49)
print(n)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [33]:
a = np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [37]:
x = np.array([1,2,0,0,4,0])
print (x[x !=0])

[1 2 4]


#### 7. Create a 3x3 identity matrix (★☆☆)

In [39]:
m = np.eye(3)
print (m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 8. Create a 3x3x3 array with random values (★☆☆)

In [43]:
b = np.random.random((3,3,3))
print (b)

[[[0.72145414 0.9622279  0.77658226]
  [0.04641159 0.71197206 0.23481151]
  [0.85404445 0.254418   0.61414349]]

 [[0.72035227 0.0330997  0.85239497]
  [0.47224997 0.1969646  0.50047702]
  [0.21519216 0.34787445 0.34546752]]

 [[0.00588578 0.21879059 0.87143651]
  [0.27011378 0.2113213  0.03334525]
  [0.26603453 0.26134118 0.16646075]]]


#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [47]:
c = np.random.random((10,10))
cmin,cmax = c.min(), c.max()
print (cmin, cmax)

0.03591191312633257 0.9949185847976046


#### 10. Create a random vector of size 30 and find the mean value (★☆☆)

In [51]:
d = np.random.random(30)
mean = d.mean()
print (mean)

0.5245517396753319


#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [70]:
e = np.diag(1+np.arange(4),k=1)
print (e)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


#### 12. Normalize a 5x5 random matrix (★☆☆)

In [76]:
f = np.random.random((5,5))
fmax, fmin = f.max(), f.min()
f = (f - fmin)/(fmax - fmin)
print(f)

[[0.87565358 0.79499953 0.05539936 0.05104427 0.96810766]
 [0.50169447 0.20766885 1.         0.17363655 0.14291364]
 [0.2573922  0.14431772 0.26066424 0.75567078 0.16413446]
 [0.34921034 0.61818291 0.45319643 0.77876845 0.02833218]
 [0.         0.6882111  0.29161094 0.12253822 0.06620491]]


#### 13. How to find common values between two arrays? (★☆☆)

In [77]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


#### 14. Create a random vector of size 10 and sort it (★★☆)

In [78]:
g = np.random.random(10)
print(g)
g.sort()
print("Sorted array:")
print(g)

[0.77685941 0.58265592 0.58660774 0.84590816 0.57148934 0.29403116
 0.42590794 0.05971857 0.96348306 0.22375782]
Sorted array:
[0.05971857 0.22375782 0.29403116 0.42590794 0.57148934 0.58265592
 0.58660774 0.77685941 0.84590816 0.96348306]


#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [79]:
g = np.random.random(10)
g[g.argmax()] = -1
print("Maximum value replaced by -1:")
print(g)

Maximum value replaced by -1:
[-1.          0.87978803  0.48769753  0.46251043  0.66023497  0.16469869
  0.58283745  0.84708451  0.43949397  0.42333891]


#### 16. Subtract the mean of each row of a matrix (★★☆)

In [80]:
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[0.04268809 0.25944394 0.50810615 0.14393192 0.12090803 0.10386341
  0.2108965  0.52012318 0.12094349 0.11790485]
 [0.96479051 0.05125637 0.48199027 0.84425141 0.28351815 0.18208547
  0.14791976 0.51968637 0.45269001 0.59762945]
 [0.89490242 0.36760029 0.58633024 0.20719377 0.73144766 0.16673687
  0.00703954 0.57176406 0.11673649 0.26875744]
 [0.2505203  0.35862921 0.5797754  0.44476359 0.43912815 0.94412515
  0.02132664 0.39342995 0.2844828  0.9846713 ]
 [0.21470014 0.39515532 0.84436761 0.56745288 0.39113861 0.95436531
  0.83425632 0.94329334 0.2627275  0.1341402 ]]

Subtract the mean of each row of the said matrix:

[[-1.72192869e-01  4.45629851e-02  2.93225192e-01 -7.09490396e-02
  -9.39729282e-02 -1.11017541e-01 -3.98445821e-03  3.05242228e-01
  -9.39374651e-02 -9.69761053e-02]
 [ 5.12208734e-01 -4.01325410e-01  2.94084966e-02  3.91669637e-01
  -1.69063625e-01 -2.70496306e-01 -3.04662016e-01  6.71045881e-02
   1.08234002e-04  1.45047669e-01]
 [ 5.03051545e-01 -2.42505867e-02  1.9

#### 17. How to get the n largest values of an array (★★★)

In [81]:
g = np.arange(10)
print("Original array:")
print(g)
np.random.shuffle(g)
n = 1
print (g[np.argsort(g)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 